import Sidebar from '@/components/Sidebar'
import './globals.css'
import { Jost } from 'next/font/google'

const jost = Jost({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${jost.className} min-h-screen bg-gray-900 flex`}>
        <Sidebar />
        {children}
      </body>
    </html>
  )
}
